POST http://localhost:1232/brands
Content-Type: application/json

{
    "name": "Brand A",
    "country": "Canada",
    "email": "branda@branda.com",
    "phone": "(111)111-1111"
}

###

POST http://localhost:1232/brands
Content-Type: application/json

{
    "name": "Brand B",
    "country": "Japan",
    "email": "brandb@brandb.com",
    "phone": "(222)222-2222"
}