POST http://localhost:6969/stores
Content-Type: application/json

{
  "name": "Test Store A",
  "store_image": "/public/images/storeA.png"
}

###
POST http://localhost:6969/stores
Content-Type: application/json

{
  "name": "Test Store B",
  "store_image": "/public/images/storeB.png"
}

###
POST http://localhost:6969/stores
Content-Type: application/json

{
  "name": "Test Store C",
  "store_image": "/public/images/storeC.png"
}

###
POST http://localhost:6969/stores
Content-Type: application/json

{
  "name": "Test Store D",
  "store_image": "/public/images/storeD.png"
}

###

GET http://localhost:6969/stores
###

GET http://localhost:6969/products
###

DELETE http://localhost:6969/products/63a410133be7003b90a282a7
###

DELETE http://localhost:6969/stores/63a41480c890993afd6f6ec5
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Red Hoodie",
  "price": 60,
  "style": "Outwear",
  "image_url": "/public/images/hoodies.png",
  "gender": "female",
  "description": "This is a hoodie."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Blue Hoodie",
  "price": 75,
  "style": "Outwear",
  "image_url": "/public/images/hoodies.png",
  "gender": "female",
  "description": "This is a hoodie."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Sweatpant",
  "price": 40,
  "style": "Bottoms",
  "image_url": "/public/images/pants.png",
  "gender": "female",
  "description": "This is a pant."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Jean",
  "price": 55,
  "style": "Bottoms",
  "image_url": "/public/images/pants.png",
  "gender": "female",
  "description": "This is a pant."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female V-Neck Shirt",
  "price": 20,
  "style": "Tops",
  "image_url": "/public/images/shirts.png",
  "gender": "female",
  "description": "This is a shirt."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Crew-Neck Shirt",
  "price": 35,
  "style": "Tops",
  "image_url": "/public/images/shirts.png",
  "gender": "female",
  "description": "This is a shirt."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Cargo Shorts",
  "price": 40,
  "style": "Bottoms",
  "image_url": "/public/images/shorts.png",
  "gender": "female",
  "description": "This is a short."
}
###

POST http://localhost:6969/products
Content-Type: application/json

{
  "store": "63a55fa7c890993afd6f747f",
  "name": "C Female Dry-Fit Shorts",
  "price": 45,
  "style": "Bottoms",
  "image_url": "/public/images/shorts.png",
  "gender": "female",
  "description": "This is a short."
}
###

